name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  mainjob:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: Test project
        run: npm run test
